name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.21.2
      - name: PHP Lint
        uses: michaelw90/PHP-Lint@2.1.0

